"""`/pegada-setup`: status line installation and ledger sharing policy."""

from __future__ import annotations

import os
import shlex
import shutil
import sys
import time
from typing import List

import pegada
from pegada_code.project import (
    LEDGER_NAME,
    ensure_gitignore,
    load_config,
    read_json,
    save_config,
    state_dir,
    write_json,
)

GITATTRIBUTES_LINE = f".claude/{LEDGER_NAME} merge=union"


def launcher_path() -> str:
    return os.path.join(state_dir(), "statusline.sh")


def launcher_command() -> str:
    return f"sh {shlex.quote(launcher_path())}"


def settings_path() -> str:
    base = os.environ.get("CLAUDE_CONFIG_DIR") or os.path.join(os.path.expanduser("~"), ".claude")
    return os.path.join(base, "settings.json")


def write_launcher() -> None:
    """The plugin directory changes on every update, so settings.json points to
    this stable launcher, which SessionStart re-points to the current version."""
    src = os.path.dirname(os.path.dirname(os.path.abspath(pegada.__file__)))
    body = (
        "#!/bin/sh\n"
        "# Generated by pegada-code. Re-pointed to the installed plugin version at every SessionStart.\n"
        f"PYTHONPATH={shlex.quote(src)}${{PYTHONPATH:+:$PYTHONPATH}} "
        f"exec {shlex.quote(sys.executable)} -m pegada code statusline\n"
    )
    with open(launcher_path(), "w", encoding="utf-8") as fh:
        fh.write(body)
    os.chmod(launcher_path(), 0o755)


def refresh_launcher() -> None:
    if os.path.exists(launcher_path()):
        write_launcher()


def install_statusline(dry_run: bool = False) -> List[str]:
    path = settings_path()
    if os.path.exists(path):
        settings = read_json(path, None)
        if not isinstance(settings, dict):
            raise SystemExit(f"{path} is not valid JSON; not modifying it.")
    else:
        settings = {}
    current = settings.get("statusLine")
    if isinstance(current, dict) and current.get("command") == launcher_command():
        if not dry_run:
            write_launcher()
        return [f"Status line already installed ({path}); launcher refreshed."]
    msgs = [f"Will set statusLine in {path} to `{launcher_command()}`."]
    if current:
        msgs.append(f"Your current status line (`{current.get('command', current)}`) will be kept: pegada appends to its output.")
    if dry_run:
        return msgs
    write_launcher()
    write_json(os.path.join(state_dir(), "statusline.json"), {"previous": current})
    if os.path.exists(path):
        backup = f"{path}.pegada-backup-{time.strftime('%Y%m%d%H%M%S')}"
        shutil.copy2(path, backup)
        msgs.append(f"Backup of settings: {backup}")
    settings["statusLine"] = {
        "type": "command",
        "command": launcher_command(),
        "padding": (current or {}).get("padding", 0) if isinstance(current, dict) else 0,
    }
    write_json(path, settings)
    msgs[0] = f"Status line installed in {path}."
    return msgs


def remove_statusline() -> List[str]:
    path = settings_path()
    settings = read_json(path, None)
    if not isinstance(settings, dict) or (settings.get("statusLine") or {}).get("command") != launcher_command():
        return ["pegada status line is not installed; nothing to do."]
    prev = read_json(os.path.join(state_dir(), "statusline.json"), {}).get("previous")
    if prev:
        settings["statusLine"] = prev
    else:
        settings.pop("statusLine", None)
    write_json(path, settings)
    return [f"Status line removed from {path}" + (" (previous one restored)." if prev else ".")]


def _read_lines(path: str) -> List[str]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as fh:
        return fh.read().splitlines()


def _write_lines(path: str, lines: List[str]) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + ("\n" if lines else ""))


def set_share(root: str, share: bool) -> List[str]:
    cfg = load_config(root)
    cfg["share"] = share
    save_config(root, cfg)
    gi = os.path.join(root, ".claude", ".gitignore")
    ga = os.path.join(root, ".gitattributes")
    if share:
        lines = [l for l in _read_lines(gi) if l.strip() != LEDGER_NAME and "pegada-code ledger" not in l]
        if os.path.exists(gi):
            _write_lines(gi, lines)
        attrs = _read_lines(ga)
        if GITATTRIBUTES_LINE not in attrs:
            _write_lines(ga, attrs + [GITATTRIBUTES_LINE])
        return [
            "Ledger sharing on: `.claude/pegada.jsonl` is no longer ignored and merges with `merge=union`.",
            "Commit `.claude/pegada.jsonl`, `.claude/pegada.config.json` and `.gitattributes`.",
            "The ledger holds model ids, token counts, timestamps and session ids — no prompts, code or paths.",
        ]
    attrs = [l for l in _read_lines(ga) if l.strip() != GITATTRIBUTES_LINE]
    if os.path.exists(ga):
        _write_lines(ga, attrs)
    ensure_gitignore(root)
    return ["Ledger sharing off: `.claude/pegada.jsonl` is git-ignored again (already committed copies stay in history)."]
